spring:
  application:
    name: auth-service

  server:
    port: 8080

  datasource:
    url: jdbc:mysql://localhost:3306/booking_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: kk
    password: Kisan@9450
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: false
    url: jdbc:mysql://localhost:3306/booking_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    user: kk
    password: Kisan@9450
    schemas: booking_platform

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  cloud:
    discovery:
      enabled: true
      eureka:
        client:
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/

jwt:
  secret-key: Z3bVj5W6QcL8I3rOjYZ0nWQsmvTjJfyKb5wXE02sJ/N2c1XqUvNpPRaAeHKP7S1JXv7X82Pfx7GuGndMCqf51w==

logging:
  level:
    org.springframework.security: DEBUG
    com.xalts.authservice: DEBUG



management:
  endpoints:
    web:
      exposure:
        include: "*"   # Expose all endpoints (health, info, metrics, etc.)
  endpoint:
    health:
      show-details: always  # Show full health details


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
